name: GKE Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GKE_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          install_components: 'kubectl'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker ${{ secrets.GCR_HOSTNAME }}
      - name: Configure Docker and GCR authentication
        env:
          GCR_HOSTNAME: "us-central1-docker.pkg.dev"  # Replace with your GCR hostname
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }} # Replace with your GCP project ID
          GCR_SA_KEY: ${{ secrets.GCR_SA_KEY }}
        run: |
          echo $GCR_SA_KEY | base64 --decode > /tmp/gcr_key.json
          docker login -u _json_key --password-stdin https://$GCR_HOSTNAME
          docker build -t $GCR_HOSTNAME/$GCP_PROJECT/container1:$GITHUB_SHA ./container1
          docker push $GCR_HOSTNAME/$GCP_PROJECT/container1:$GITHUB_SHA      
      

      - name: Build and push Docker image (Container 1)
        run: |
          docker build -t ${{ secrets.GCR_HOSTNAME }}/${{ secrets.GCP_PROJECT }}/container1:$GITHUB_SHA ./container1
          docker push ${{ secrets.GCR_HOSTNAME }}/${{ secrets.GCP_PROJECT }}/container1:$GITHUB_SHA

      - name: Build and push Docker image (Container 2)
        run: |
          docker build -t ${{ secrets.GCR_HOSTNAME }}/${{ secrets.GCP_PROJECT }}/container2:$GITHUB_SHA ./container2
          docker push ${{ secrets.GCR_HOSTNAME }}/${{ secrets.GCP_PROJECT }}/container2:$GITHUB_SHA

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }} --project ${{ secrets.GCP_PROJECT }}

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/container1 container1=${{ secrets.GCR_HOSTNAME }}/${{ secrets.GCP_PROJECT }}/container1:$GITHUB_SHA
          kubectl set image deployment/container2 container2=${{ secrets.GCR_HOSTNAME }}/${{ secrets.GCP_PROJECT }}/container2:$GITHUB_SHA
